### ISSUE TITLE
Liquid tags should be ignored

### ISSUE THREAD

**Issue by jrha** [stfc/markdown-spellchecker#9] opened 2018-05-23 22:04 UTC
e.g. `{% include ... %}`

**Comment by jouvin** [comment] 2018-05-24 07:56
This should also include more complex Liquid tags that have an opening and closing tag. Unfortunately, AFAIK, there is no way to anticipate that the tag as a closing part. One of the important tag like this is:

```
{% comment %}
this is a comment line 
or paragraph
{% endcomment %}
```

**Comment by jouvin** [comment] 2018-05-24 08:08
Another construct not properly handled is the Markdown LinkID definition:

```
[linkid]: url
```
optionally followed by a few URL parameters as a succession of lines like:
```
{:param="value"}
```
Look at https://github.com/quattor/quattor.github.com/blob/master/_includes/link_definitions.md for an example.

**Comment by jrha** [comment] 2018-05-24 16:26
@jouvin #10 should deal with most of this, I'm not convinced that comments should be ignored though

**Comment by jouvin** [comment] 2018-05-24 16:56
The problem is that in comment you may put URL without any markup and all this things tend to be a problem for the spell checker. In principle I'd agree with you but as this is not text exposed to the users, may be it is acceptable to ignore it rather than to deal will all the unexpected words you may want to put here. I'd not expect to find many comments anyway in a markdown file.

**Comment by jrha** [comment] 2018-05-24 16:57
URLs should be correctly detected by the spellchecker, if not then that is a different bug.

**Comment by jouvin** [comment] 2018-05-24 16:59
URL is probably not a good example. But imagine a comment like `aqd.conf.defaults must be fixed first`. I have the feeling (it was my experience) that `aqd`, `conf` and `defaults` will be checked and obviously `aqd` will fail....

**Closed as completed** 2018-06-19 13:58 UTC
